[package]
name = "motion-detector-raw"
version = "0.1.0"
edition = "2021"

[dependencies]
make87 = "*"
make87_messages = ">=0.2.8"
opencv = { version="0.94.4", features = ["clang-runtime"] }
log = "0.4.27"
